services:
  redis:
    image: redis:7-alpine
    container_name: redis-ephemeral
    command:
      ['redis-server', '--save', '', '--appendonly', 'no', '--requirepass', '${REDIS_PASSWORD}']
    ports:
      - '6379:6379'
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq-ephemeral
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - '5672:5672' # AMQP
      - '15672:15672' # HTTP management UI
    restart: unless-stopped
  postgres:
    image: postgres:16-alpine
    container_name: postgres-ephemeral
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    restart: unless-stopped
